apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-virtiofs-mysql-01
  namespace: wordpress-dev
  labels:
    pvc-app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /srv/virtiofs/mysql
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: mysql-pv-claim
    namespace: wordpress-dev
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sworker01
          - k8sworker02

