---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: wp-vpa
  namespace: wordpress-dev
spec:
  # recommenders field can be unset when using the default recommender.
  # When using an alternative recommender, the alternative recommender's name
  # can be specified as the following in a list.
  # recommenders:
  #   - name: 'alternative'
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: wordpress
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 10m
          memory: 50Mi
        maxAllowed:
          cpu: 1
          memory: 500Mi
        controlledResources: ["cpu", "memory"]
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-wp-dev
  namespace: wordpress-dev
  labels:
    app: wordpress-wp-dev
spec:
  ports:
    - port: 8091
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: ClusterIP
  externalIPs:
    - 10.192.168.202
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-dev-01-pv-claim
  namespace: wordpress-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress-dev
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-dev-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_USER
          value: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
        imagePullPolicy: Always
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-dev-01-pv-claim
