apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-virtiofs-wordpress-wp-dev-01
  namespace: wordpress-wp-dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /srv/virtiofs/wordpress
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: wp-dev-01-pv-claim
    namespace: wordpress-dev
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - controlplane

