pvc:
  name: kubewall-data  # Name of the PVC
  storage: 50Mi  # Storage size requested for the PVC
  accessModes: ReadWriteOnce  # Access mode for the PVC
  storageClass: "local-path"  # Storage class for the PVC (leave empty for default)
resources:
  limits:
    cpu: 500m
    memory: 512Mi  # Maximum memory limit (128 MiB)
  requests:
    cpu: 100m  # Minimum CPU request (100 milli-CPU)
    memory: 256Mi  # Minimum memory request (128 MiB)
