global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '<xxx>'
  resolve_timeout: 5m
route:
  group_by: ['alertname','job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'smtp'
  routes:
receivers:
- name: 'smtp'
  email_configs:
  - to: '<xxx>'
    auth_username: '<xxx>'
    auth_password: '<xxx>'
    require_tls: true
    send_resolved: true
templates:
- '/etc/alertmanager/config/*.tmpl'
