prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
grafana:
  defaultDashboardsTimezone: Europe/Bratislava
  persistence:
    enabled: true
    #type: sts
    storageClassName: "local-storage"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
config:
  route:
    receiver: smtp
  receivers:
    - name: smtp
      email_configs:
          - smarthost: smtp.gmail.com:587
            to: 'xxx'
            from: 'xxx'
            auth_username: 'xxx'
            auth_password: 'xxx'
            send_resolved: true
            require_tls: false
