prometheus:
  service:
    externalIPs:
      - 10.192.168.202
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
grafana:
  defaultDashboardsTimezone: Europe/Bratislava
  service:
    port: 3000
    externalIPs:
      - 10.192.168.202
  grafana.ini:
    server:
      domain: "k8smaster.local"
      root_url: "%(protocol)s://%(domain)s/"
      serve_from_sub_path: true
  persistence:
    enabled: true
    storageClassName: "local-storage"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
alertmanager:
  alertmanagerSpec:
    useExistingSecret: true
    secrets:
      - alertmanager-prometheus-kps-kube-promet-alertmanager

