prometheus:
  service:
    externalIPs:
      - 10.192.168.202
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
grafana:
  defaultDashboardsTimezone: Europe/Bratislava
  service:
    port: 3000
    externalIPs:
      - 10.192.168.202
  grafana.ini:
    server:
      domain: "k8smaster.local"
      root_url: "%(protocol)s://%(domain)s/"
      serve_from_sub_path: true
  persistence:
    enabled: true
    storageClassName: "local-storage"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: '<xxx>@gmail.com'
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'smtp'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'smtp'
    receivers:
    - name: 'smtp'
      email_configs:
      - to: '<xxx>@gmail.com'
        auth_username: '<xxx>@gmail.com'
        auth_password: '<xxx>'
        require_tls: true
        send_resolved: true
    templates:
    - '/etc/alertmanager/config/*.tmpl'
