apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-virtiofs-prometheus-01
  namespace: monitoring
  labels:
    pvc-app: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /srv/virtiofs/prometheus
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: prometheus-prometheus-kps-kube-promet-prometheus-db-prometheus-prometheus-kps-kube-promet-prometheus-0
    namespace: monitoring
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sworker01
          - k8sworker02

